name: Deploy Link SDK

on:
  workflow_dispatch:

jobs:
  build-test-and-deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout 🎾
        uses: actions/checkout@v4

      - name: Setup Java ♨️
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Setup Android SDK 🎁
        uses: android-actions/setup-android@v3

      - name: Run code quality checks 🧹
        run: ./gradlew link:ktlintCheck link:detekt link:lintRelease

      - name: Run tests & coverage verification 🥁
        run: ./gradlew link:jacocoCoverageVerification

      - name: Build 🧩
        run: ./gradlew link:assembleRelease

      - name: Publish release 🎉
        run: ./gradlew link:publishAndReleaseToMavenCentral --no-configuration-cache
        env:
          ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.MAVEN_USERNAME }}
          ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.MAVEN_PASSWORD }}
          ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.SIGNING_KEY }}
          ORG_GRADLE_PROJECT_signingInMemoryKeyPassword: ${{ secrets.SIGNING_PASSWORD }}

      - name: Run sonar ✅
        run: ./gradlew link:sonar
        env:
          ORG_GRADLE_PROJECT_sonarProjectKey: ${{ vars.SONAR_PROJECT_KEY }}
          ORG_GRADLE_PROJECT_sonarOrganization: ${{ vars.SONAR_ORGANIZATION }}
          ORG_GRADLE_PROJECT_sonarHostUrl: ${{ vars.SONAR_HOST_URL }}
          ORG_GRADLE_PROJECT_sonarToken: ${{ secrets.SONAR_TOKEN }}

      - name: Push git tag ☀️
        run: |
          NEW_TAG=$(grep "mesh-link" gradle/libs.versions.toml -m 1 | cut -d "=" -f2 | xargs)
          git tag $NEW_TAG
          git push origin $NEW_TAG
