name: CI

on:
  pull_request:
    branches:
      - main

jobs:
  checks:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout 🎾
        uses: actions/checkout@v4

      - name: Setup Java ♨️
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: 17

      - name: Setup Android SDK 🎁
        uses: android-actions/setup-android@v3

      - name: Run ktlint & detekt 🧹
        run: ./gradlew link:ktlintCheck link:detekt

      - name: Run lint 🧼
        run: ./gradlew link:lintRelease

      - name: Run tests & coverage verification 🥁
        run: ./gradlew link:jacocoCoverageVerification

      - name: Build 🧩
        run: ./gradlew link:assembleRelease

      - name: Run sonar ✅
        timeout-minutes: 10
        run: ./gradlew link:sonar
        env:
          ORG_GRADLE_PROJECT_sonarProjectKey: ${{ vars.SONAR_PROJECT_KEY }}
          ORG_GRADLE_PROJECT_sonarOrganization: ${{ vars.SONAR_ORGANIZATION }}
          ORG_GRADLE_PROJECT_sonarHostUrl: ${{ vars.SONAR_HOST_URL }}
          ORG_GRADLE_PROJECT_sonarToken: ${{ secrets.SONAR_TOKEN }}
